class FsConstants:
    CLUSTER_SIZE = 1024
    CLUSTER_COUNT = 1024

    SUPERBLOCK_CLUSTER = 0
    FAT_START_CLUSTER = 1
    FAT_END_CLUSTER = 4
    CONTENT_START_CLUSTER = 6
    ROOT_DIR_FIRST_CLUSTER = 5
